version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: healthcare-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: healthcare-frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true